config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { invitations: 'users/invitations', sessions: 'users/sessions' }
  devise_scope :user do
    match 'active' => 'users/sessions#active', via: :get
    match 'timeout' => 'users/sessions#timeout', via: :get
    match 'users/invitations/confirm', via: :post
  end

  namespace :users do
    resources :invitations do
      collection do
        post :confirm
      end
    end
  end

  concern :restorable do
    member { post 'restore' }
  end

  resources :clients, only: [:index, :show, :update] do
    resource :contacts, only: [:edit, :update], controller: :client_contacts, concerns: [:restorable]
    resource :contact, only: [:edit, :update], controller: :client_contact
    patch :unavailable, on: :member
    resources :unavailable_on_route, only: [:destroy]
    resources :matches, controller: 'client_matches', only: :index
    resources :closed_matches, controller: 'client_closed_matches', only: :index
    resources :client_notes, controller: 'client_notes', only: [:index, :destroy, :create]
    resources :qualified_opportunities, only: [:index, :update]
  end
  resources :unavailable_clients, only: [:index]
  resources :opportunities do
    post 'restore'
    resources :contacts, except: :show, controller: :opportunity_contacts, concerns: [:restorable]
    resources :matches, controller: 'opportunity_matches', only: [:index, :create, :update] do
      get :all, on: :collection
      get :closed, on: :collection
    end
  end
  resources :buildings do
    resources :contacts, except: :show, controller: :building_contacts, concerns: [:restorable]
    get :available_units, on: :member
    get :available_move_in_units, on: :member
    get :available_units_for_vouchers, on: :member
    get :units, on: :member
    resources :units, only: :new
    resources :housing_attributes, module: 'buildings' do
      post :values, on: :collection
    end
    resources :housing_media_links, module: 'buildings'
  end
  resources :subgrantees do
    resources :contacts, except: :show, controller: :subgrantee_contacts, concerns: [:restorable]
  end
  resources :rules do
    get 'confirm_destroy', on: :member
    post 'restore', on: :member
  end
  resources :services, except: :show
  resources :funding_sources

  # concern that we can drop in at top level too
  # matches and their stuff can either be accessed directly if the user is logged in
  # or via a notification code
  def manage_matches
    resources :matches, only: [:show, :update] do
      get :history
      resources :decisions, only: [:show, :update], controller: 'match_decisions' do
        resource :acknowledgment, only: [:create], controller: 'match_decision_acknowledgments'
        get :recreate_notifications, on: :member
        get :recreate_hsa_notifications_nine, on: :member
      end

      resource :contacts, only: [:edit, :update], controller: 'match_contacts'
      resources :notes, only: [:new, :create, :edit, :update, :destroy], controller: 'match_notes'
      resource :client_details, only: [:show], controller: 'match_client_details'
      resources :match_progress_updates, only: [:create], shallow: true
      resources :match_progress_update_notes, only: [:edit, :update, :destroy]
      get :reopen
    end
  end
  manage_matches

  resources :active_matches, only: :index
  resources :closed_matches, only: :index

  # also temporary, for testing
  namespace :testing do
    namespace :matching do
      resources :candidate_generations, only: [:new, :create]
    end
  end

  resources :notifications, only: [:show] do
    manage_matches

    resources :buildings, only: :show do
      get :available_move_in_units, on: :member
    end

    resource :reissue_request, only: [:show]
    devise_scope :user do
      resources :sessions, only: [:new, :create], controller: 'notification_sessions'
      resources :registrations, only: [:new, :create], controller: 'notification_registrations'
    end
  end

  resources :contacts, only: [:index] do
    member do
      get :move_matches
      post :update_matches
    end
  end
  resources :units, except: :show, concerns: [:restorable] do
    post :deactivate
    resources :housing_attributes, module: 'units' do
      post :values, on: :collection
    end
    resources :housing_media_links, module: 'units'
  end
  resources :programs do
    resources :sub_programs, only: [:new, :edit, :create, :update, :destroy] do
      member do
        get :close
      end

      resource :contacts, only: [:edit, :update], controller: :sub_program_contacts
      resources :vouchers, only: [:index, :edit, :create, :update, :destroy] do
        patch 'bulk_update', on: :collection
        delete :unavailable, on: :member
        patch 'archive', on: :member
      end
      resources :in_progress_vouchers, only: [:index, :create, :update, :destroy] do
        patch 'bulk_update', on: :collection
        delete :unavailable, on: :member
      end
      resources :successful_vouchers, only: [:index, :create, :update, :destroy] do
        patch 'bulk_update', on: :collection
        delete :unavailable, on: :member
      end
      resource :program_details, only: [:edit, :update]
      resources :unit_for_building, only: [:new, :edit, :create, :update]
    end
  end
  resources :services

  namespace :admin do
    # resolves route clash w/ devise
    resources :users, except: [:show, :new, :create] do
      resource :resend_invitation, only: :create
      resource :recreate_invitation, only: :create
      resource :audit, only: :show
      resource :edit_history, only: :show
      resource :locations, only: :show
      patch :reactivate, on: :member
      member do
        post :confirm
        post :impersonate
      end
      collection do
        post :stop_impersonating
      end
    end
    resources :agencies do
      post :move_user
    end
    resources :roles
    resources :versions, only: [:index]

    resources :translation_keys, only: [:index, :update]
    resources :translation_text, only: [:update]
    resources :configs, only: [:index] do
      patch :update, on: :collection
    end
    resources :match_routes, only: [:index, :edit, :update] do
      resources :weighting_rules, on: :member, except: [:create]
    end
    resources :sessions, only: [:index, :destroy]
  end

  resources :neighborhoods
  resources :tags

  resource :account, only: [:edit, :update] do
    get :locations, on: :member
  end
  resource :account_email, only: [:edit, :update]
  resource :account_password, only: [:edit, :update]

  resources :resend_notification, only: [:show]

  resources :reports, only: [:index]
  namespace :reports do
    resources :parked_clients, only: [:index]
    namespace :dashboards do
      resources :overviews, only: [:index] do
        collection do
          get :details
        end
      end
      resources :contacts, only: [:index] do
        collection do
          get :details
        end
      end
      resources :vacancies, only: [:index] do
        collection do
          get :details
        end
      end
      resources :time_between_steps, only: [:index] do
        collection do
          get :details
          get :step_name_options
        end
      end
      resources :clients, only: [:index] do
        collection do
          get :client_details
          get :matches_details
        end
      end
    end
    resources :match_progress, only: [:index]
    resources :housed_addresses, only: [:index]
    resources :agency_interactions, only: [:index]
    resources :external_referrals, only: [:index] do
      collection do
        post :refer
      end
    end
  end

  namespace :system_status do
    get :operational
    get :cache_status
    get :details
    get :ping
  end
  get 'healthz' => 'system_status#operational'

  resources :deidentified_clients do
    resources :non_hmis_assessments do
      patch :unlock, on: :member
    end
    collection do
      get :choose_upload
      post :import
    end
    member do
      get :current_assessment_limited
      patch :shelter_location
    end
  end
  resources :identified_clients do
    resources :non_hmis_assessments do
      patch :unlock, on: :member
    end
    member do
      get :current_assessment_limited
      patch :shelter_location
    end
  end
  resources :imported_clients
  resources :messages, only: [:show, :index] do
    collection do
      get :poll
      post :seen
    end
  end

  resources :help

  unless Rails.env.production?
    resources 'style_guides', only: :index do
      get 'dnd_match_review', on: :collection
      get 'icon_font', on: :collection
      get 'match_contacts_modal', on: :collection
      get 'stepped_progress', on: :collection
      get 'tags', on: :collection
      get 'typography', on: :collection
      get 'summary', on: :collection
      get 'pagination', on: :collection
      get 'form', on: :collection
    end
  end

  root 'root#index'
end

app/helpers/match_list_base_helper.rb
###
# Copyright 2016 - 2024 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/boston-cas/blob/production/LICENSE.md
###

module MatchListBaseHelper

  def search_directions
    columns = ['created_at']
    @_search_directions ||= current_sort_order Hash[columns.map {|x| [x, nil]}]
  end

  def show_match_status_facet_nav?
    current_user.can_view_all_matches? || current_user.can_view_own_closed_matches?
  end

  def show_links_to_matches?
    true
  end

end

app/views/match_list_base/_current_step.haml
- match_route = match.match_route
- types = match_step_types[match_route.class.name]
- match_decisions = match.decisions.order(id: :asc).where(type: types&.keys).to_a
- size ||= 'lg'
- small_class = 'c-stepped-progress--sm'

.d-flex
  %ol.c-stepped-progress{"step-count" => "#{match_decisions.count}", class: "#{small_class if size == 'sm'} route-#{match_route.class.name.parameterize}"}
    - match_decisions.each do |decision|
      - decision_status = decision.incomplete_active_done?
      - next_decision = match_decisions.detect{|md| md.type == types.keys[types.keys.index(decision.type) + 1]}
      - final = types[decision.type].to_i == types.length.to_i
      -# if a step is canceled, but the next step has a status
      - if decision_status == :canceled && (next_decision.present? && next_decision.status.present?)
        - decision_status = :done
      %li{class: "c-stepped-progress__step c-stepped-progress__step--#{decision_status} #{ 'c-stepped-progress__step--final' if final}"}
        .sr-only
          = decision.step_name
        - if size == 'sm'
          - link = '#'
          - if can_reject_matches? || match.on_or_after_first_client_step?
            - link = match_path(match)
          = link_to link, class: 'c-stepped-progress__step-link', data: {toggle: :tooltip, title: decision.step_name} do
            .c-stepped-progress__step-number= types[decision.type]
        - else
          .c-stepped-progress__step-link--static{data: {toggle: :tooltip, title: decision.step_name}}
            .c-stepped-progress__step-number= types[decision.type]

app/views/match_list_base/_filter.haml
- if @active_filter
  - filter_class = 'filter-sort__filter-active'
- else
  - filter_class = 'filter-sort__filter'
.o-filtration.o-filtration--sm.dropdown{class: filter_class}
  %button.btn.btn-light.dropdown-toggle.mr-4{data: {toggle: 'dropdown'}}
    Filter
    %span.caret
  .o-filtration__container.dropdown-menu.dropdown-menu.options{aria:{labelledby:"filter-dropdown"}}
    .o-filtration__header
      %h3.client__filter-header Filter matches

    = form_tag(nil, method: "get") do
      -# preserve sort and search for filtering
      -# preserve sort and search for filtering
      - if params[:sort]
        = hidden_field_tag :sort, params[:sort]
      - if params[:direction]
        = hidden_field_tag :direction, params[:direction]
      - if params[:q]
        = hidden_field_tag :q, params[:q]
      - if params[:current_route]
        = hidden_field_tag :current_route, params[:current_route]

      .o-filtration__option
        %select.select2{name: :current_step, style: 'width: 100%;', data: { 'dropdown-parent' => '.o-filtration__container form' }}
          %option{value: ''} Filter by Current Step
          - available_steps.each do |label,value|
            - selected = @current_step == value
            %option{value: value, selected: selected}
              = label

      .o-filtration__option
        %select.select2{name: :current_program, style: 'width: 100%;', data: { 'dropdown-parent' => '.o-filtration__container form' }}
          %option{value: ''} Filter by Program
          - available_programs.each do |program|
            - selected = @current_program.to_i == program.id
            %option{value: program.id, selected: selected}
              = program.name

      - if current_user.can_view_all_matches?
        .o-filtration__option
          %select.select2{name: :current_filter_contact, style: 'width: 100%;', data: { 'dropdown-parent' => '.o-filtration__container form' }}
            %option{value: ''} Filter by Contact
            - Contact.active_contacts.each do |contact|
              - selected = @current_filter_contact&.to_i == contact.id
              %option{value: contact.id, selected: selected}
                = contact.name

      .o-filtration__option
        %select.select2{name: :current_contact_type, style: 'width: 100%;', data: { 'dropdown-parent' => '.o-filtration__container form' }}
          %option{value: ''} Filter by Contact Type
          - MatchContacts.input_names.each do |contact_type|
            - selected = @current_contact_type == contact_type
            %option{value: contact_type, selected: selected}
              = Contact::label_for(contact_type)&.gsub('Contacts', 'Contact')

      .o-filtration__actions.form__actions
        = link_to(filter_params.merge(action: :index), class: 'btn btn-light')do
          %i.icon-cross
          Clear
        %button.btn.btn-primary.ml-auto{type: :submit}
          %i.icon-filter
          Filter

= render 'init_select2'

app/views/match_list_base/_help_text.haml
-# to display help text for a particular match listing, override this partial in the view folder that corresponds to the particular controller subclass

app/views/match_list_base/_show_confidential_names.haml
- if can_view_client_confidentiality?
  - if show_confidential_names?
    = link_to 'Hide Confidential Names', request.query_parameters.except(:confidential_override), class: 'btn btn-light ml-auto align-self-start'
  - else
    = link_to 'Show Confidential Names', request.query_parameters.merge({confidential_override: true}), class: 'btn btn-outline-danger ml-auto align-self-start '

app/views/match_list_base/_tabs.haml
- if available_routes.count > 1
  %ul.nav.nav-tabs{role: :tablist}
    - available_routes.each do |route|
      - route_name = route.first
      - if current_tab == route_name
        - active = 'active'
      - else
        - active = ''
      %li.nav-item{role: :presentation}
        = link_to route_name, filter_params.merge(action: :index, current_route: route_name), class: "nav-link #{active}"